name: flutter_app
description: Stroke Detection Frontend
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6             # HTTP client for sending requests
  image_picker: ^1.0.4      # Optional if you want to capture video from camera/gallery
  camera: ^0.9.4+5          # For live camera feed recording
  file_picker: ^5.2.5       # For selecting local video files
  path_provider: ^2.1.1     # For accessing file paths if needed
  fluttertoast: ^8.0.8      # For user feedback

flutter:
  uses-material-design: true
